// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pos.infrastructure.Data;

#nullable disable

namespace pos.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801061303_CreateTableCompany")]
    partial class CreateTableCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pos.domain.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<Guid>("CompanyGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company_name");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_datetime");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyGuid")
                        .HasDatabaseName("ix_company_company_guid");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CompanyGuid"), false);

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("pos.domain.Entities.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("BitActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bit_active");

                    b.Property<bool>("BitBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bit_blocked");

                    b.Property<bool>("BitSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bit_super_admin");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_datetime");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email_address");

                    b.Property<string>("MobileNo")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mobile_no");

                    b.Property<string>("MobileNoCountryCode")
                        .HasColumnType("varchar(4)")
                        .HasColumnName("mobile_no_country_code");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("staff_name");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPINHash")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_pin_hash");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_user_account_company_id");

                    b.ToTable("user_account", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
